import SmallCard2 from "@/components/common/productCard/SmallCard2";
import ProductCard1 from "@/components/common/ProductCard1";
import ProductCard2 from "@/components/common/ProductCard2";
import ProductCard3 from "@/components/common/ProductCard3";
import ProductCard4 from "@/components/common/ProductCard4";
import ProductFloat from "@/components/common/ProductFloat";
import Banner1 from "@/components/home/Banner1";
import Brand from "@/components/home/Brand";
import SwapCardBanner from "@/components/home/SwapCardBanner/SwapCardBanner";
import { banner1Items } from "@/mockup/banner1";
import { IProduct, products } from "@/mockup/product";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";

type Props = {
  bannerProducts: {
    swapCard: [IProduct, IProduct];
  };
};

const Home: NextPage<Props> = ({ bannerProducts }) => {
  return (
    <>
      <Head>
        <title>Medicine store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="3xl:max-w-[2560px] mx-auto">
          <Brand />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto">
          <Banner1 items={banner1Items} />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto rounded-b-xl overflow-hidden mb-8">
          <SwapCardBanner products={bannerProducts.swapCard} />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto pb-4 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductFloat
            product={products[5]}
            backgroundImage={{
              src: "/assets/ingredient-bg.png",
              alt: "ingredient",
            }}
          />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto pb-0 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductFloat
            product={products[6]}
            backgroundImage={{
              src: "/assets/ingredient-bg.png",
              alt: "ingredient",
            }}
          />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto py-6 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductCard1
            productBig={products[0]}
            productTopRight={products[1]}
            productBottomRight={products[2]}
          />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto pb-6 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductCard2
            productBig={products[0]}
            productTopRight={products[1]}
            productBottomRight={products[2]}
          />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto pb-6 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductCard3 productLeft={products[3]} productRight={products[4]} />
        </section>
        <section className="3xl:max-w-[2560px] mx-auto pb-6 3xl:px-44 2xl:px-36 xl:px-6">
          <ProductCard4 product={products[6]} />
        </section>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async (ctx) => {
  return {
    props: {
      bannerProducts: {
        swapCard: [products[7], products[8]],
      },
    },
  };
};

export default Home;
